# Generated by Django 4.0.3 on 2022-04-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_videos_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
